#!/bin/bash

if [[ $# -eq 1 ]]
then
	sandbox_org_alias=$1
else
	read -p "Org alias? " sandbox_org_alias
fi

echo "sfdx force:auth:web:login -r https://test.salesforce.com -a $sandbox_org_alias"
sfdx force:auth:web:login -r https://test.salesforce.com -a $sandbox_org_alias

