#!/bin/bash


if [[ $# -eq 1 ]]
then
	org_alias=$1
else
	read -p "Sandbox org alias? " org_alias
fi

echo "sf login org -a ${org_alias} -l https://test.salesforce.com"
sf login org -a ${org_alias} -l https://test.salesforce.com
