#!/bin/bash

if [[ $# -eq 1 ]]
then
	scratch_org_alias=$1
else
	read -p "Scratch org alias? " scratch_org_alias
fi

echo "[info] sfdx force:org:create -s -f config/project-scratch-def.json -a $scratch_org_alias"
sfdx force:org:create -s -f config/project-scratch-def.json -a $scratch_org_alias
echo "[info] sfdx force:user:password:generate -u $scratch_org_alias"
sfdx force:user:password:generate -u $scratch_org_alias
echo "[info] sfdx force:org:display"
sfdx force:org:display

