#!/bin/bash

echo "sfdx force:project:create -n $1 --manifest"
sfdx force:project:create -n $1 --manifest
mkdir $1/docs $1/scripts

echo "*** You should really update the config/scratch org def file with your email"
echo 
echo "Add \"adminEmail\": \"Your.Email@Company.com\", after \"edition\"."
echo "Add \"hasSampleData\": true,"
echo "Add .forceignore and .gitignore"
echo


