#!/bin/bash

## Open either a specific org or the default org
if [[ $# -eq 1 ]]
then
	echo "sf org open -o $1"
	sf org open -o $1
	exit $?
fi

echo "sf org open"
sf org open

exit $?

## ################################################################################
## Older Commands
## ################################################################################
if [[ $# -eq 1 ]]
then
	echo "sfdx force:org:open -u $1"
	sfdx force:org:open -u $1
	exit $?
fi

echo "sfdx force:org:open"
sfdx force:org:open
exit $?
