#!/bin/bash

if [[ $# -eq 2 ]]
then
	file_name=$1
	alias_name=$2
else
	read -p "Apex Script Name? " file_name
	read -p "Org Alias? " alias_name
fi

echo "[info] sfdx force:apex:execute -f ${file_name} -u ${alias_name}"
sfdx force:apex:execute -f ${file_name} -u ${alias_name}



