#!/bin/bash

if [[ $# -eq 2 ]]
then
	file_name=$1
	alias_name=$2
else
	read -p "SOQL File Name? " file_name
	read -p "Org Alias? " alias_name
fi

if [[ ! -f ${file_name} ]]
then
	echo "ERROR: ${file_name} not found"
	exit 1
fi

soql=$(cat ${file_name})

echo "sfdx force:data:soql:query -q \"${soql}\" -u ${alias_name}"
sfdx force:data:soql:query -q "${soql}" -u ${alias_name}



