#!/bin/bash

function fail {
	echo "ERROR: $@"
	exit 1
}

if [[ $# -eq 1 ]]
then
	scratch_org_alias=$1
else
	read -p "Scratch org alias? " scratch_org_alias
fi

echo "sfdx force:config:set defaultusername=${scratch_org_alias}"
sfdx force:config:set defaultusername=${scratch_org_alias} || \
	fail "Could not create scratch org"

echo "sfdx force:org:display"
sfdx force:org:display || \
	fail "Could not display scratch org details"

exit 0

