#!/bin/bash

if [[ $# -eq 2 ]]
then
	file_name=$1
	alias_name=$2
elif [[ $# -eq 1 ]]
then
	file_name=$1
	echo "Running [${file_name}] in default org..."
	echo "sf data query -f ${file_name}"
	sf data query -f "${file_name}"
	exit $?
else
	read -p "SOQL File Name? " file_name
	read -p "Org Alias? " alias_name
fi


echo "sf data query -f ${file_name} -o ${alias_name}"
sf data query -f ${file_name} -o ${alias_name}
exit $?


